plugin:
    name: 'timfoerster.leaflet::lang.plugin.name'
    description: 'timfoerster.leaflet::lang.plugin.description'
    author: 'Tim Foerster'
    icon: icon-map-marker
    homepage: 'https://github.com/TimFoerster/octobercms-leaflet'
navigation:
    main-menu-item:
        label: Maps
        url: timfoerster/leaflet/maps
        icon: icon-map-marker
        permissions: ['timfoerster.leaflet.*']
